apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: cert-manager-helm-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      control-plane: controller-manager
