# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.cert-manager.io_operatorconfigs.yaml
- bases/cert-manager.io_crds.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
